# Form implementation generated from reading ui file 'UI_Calculator.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(370, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(370, 530))
        MainWindow.setMaximumSize(QtCore.QSize(370, 530))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DialogWarning")
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"border: none;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(370, 530))
        self.centralwidget.setMaximumSize(QtCore.QSize(370, 530))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 4, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_mult = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mult.sizePolicy().hasHeightForWidth())
        self.btn_mult.setSizePolicy(sizePolicy)
        self.btn_mult.setMinimumSize(QtCore.QSize(77, 70))
        self.btn_mult.setMaximumSize(QtCore.QSize(77, 80))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_mult.setFont(font)
        self.btn_mult.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_mult.setStyleSheet("background-color: rgb(254, 160, 10);\n"
"color: rgb(250, 250, 250);\n"
"border: none;")
        self.btn_mult.setCheckable(True)
        self.btn_mult.setAutoDefault(False)
        self.btn_mult.setDefault(False)
        self.btn_mult.setFlat(False)
        self.btn_mult.setObjectName("btn_mult")
        self.gridLayout_2.addWidget(self.btn_mult, 2, 3, 1, 1)
        self.btn_number2 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number2.sizePolicy().hasHeightForWidth())
        self.btn_number2.setSizePolicy(sizePolicy)
        self.btn_number2.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number2.setMaximumSize(QtCore.QSize(90, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number2.setFont(font)
        self.btn_number2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number2.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number2.setCheckable(True)
        self.btn_number2.setAutoDefault(False)
        self.btn_number2.setDefault(False)
        self.btn_number2.setFlat(False)
        self.btn_number2.setObjectName("btn_number2")
        self.gridLayout_2.addWidget(self.btn_number2, 4, 1, 1, 1)
        self.btn_number4 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number4.sizePolicy().hasHeightForWidth())
        self.btn_number4.setSizePolicy(sizePolicy)
        self.btn_number4.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number4.setMaximumSize(QtCore.QSize(95, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number4.setFont(font)
        self.btn_number4.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number4.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number4.setCheckable(True)
        self.btn_number4.setAutoDefault(False)
        self.btn_number4.setDefault(False)
        self.btn_number4.setFlat(False)
        self.btn_number4.setObjectName("btn_number4")
        self.gridLayout_2.addWidget(self.btn_number4, 3, 0, 1, 1)
        self.btn_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_plus.sizePolicy().hasHeightForWidth())
        self.btn_plus.setSizePolicy(sizePolicy)
        self.btn_plus.setMinimumSize(QtCore.QSize(77, 70))
        self.btn_plus.setMaximumSize(QtCore.QSize(77, 80))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_plus.setFont(font)
        self.btn_plus.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_plus.setStyleSheet("background-color: rgb(254, 160, 10);\n"
"color: rgb(250, 250, 250);\n"
"border: none;")
        self.btn_plus.setCheckable(True)
        self.btn_plus.setAutoDefault(False)
        self.btn_plus.setDefault(False)
        self.btn_plus.setFlat(False)
        self.btn_plus.setObjectName("btn_plus")
        self.gridLayout_2.addWidget(self.btn_plus, 4, 3, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_clear.setMaximumSize(QtCore.QSize(95, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_clear.setFont(font)
        self.btn_clear.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_clear.setStyleSheet("QPushButton {\n"
"background-color: rgb(100, 100, 100);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(90, 90, 90);\n"
"}")
        self.btn_clear.setCheckable(True)
        self.btn_clear.setAutoDefault(False)
        self.btn_clear.setDefault(False)
        self.btn_clear.setFlat(False)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_2.addWidget(self.btn_clear, 1, 0, 1, 1)
        self.btn_number3 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number3.sizePolicy().hasHeightForWidth())
        self.btn_number3.setSizePolicy(sizePolicy)
        self.btn_number3.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number3.setMaximumSize(QtCore.QSize(85, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number3.setFont(font)
        self.btn_number3.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number3.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number3.setCheckable(True)
        self.btn_number3.setAutoDefault(False)
        self.btn_number3.setDefault(False)
        self.btn_number3.setFlat(False)
        self.btn_number3.setObjectName("btn_number3")
        self.gridLayout_2.addWidget(self.btn_number3, 4, 2, 1, 1)
        self.btn_division = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_division.sizePolicy().hasHeightForWidth())
        self.btn_division.setSizePolicy(sizePolicy)
        self.btn_division.setMinimumSize(QtCore.QSize(77, 70))
        self.btn_division.setMaximumSize(QtCore.QSize(77, 80))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_division.setFont(font)
        self.btn_division.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_division.setStyleSheet("background-color: rgb(254, 160, 10);\n"
"color: rgb(250, 250, 250);\n"
"border: none;")
        self.btn_division.setCheckable(True)
        self.btn_division.setAutoDefault(False)
        self.btn_division.setDefault(False)
        self.btn_division.setFlat(False)
        self.btn_division.setObjectName("btn_division")
        self.gridLayout_2.addWidget(self.btn_division, 1, 3, 1, 1)
        self.btn_decimal = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_decimal.sizePolicy().hasHeightForWidth())
        self.btn_decimal.setSizePolicy(sizePolicy)
        self.btn_decimal.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_decimal.setMaximumSize(QtCore.QSize(95, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_decimal.setFont(font)
        self.btn_decimal.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_decimal.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_decimal.setCheckable(True)
        self.btn_decimal.setAutoDefault(False)
        self.btn_decimal.setDefault(False)
        self.btn_decimal.setFlat(False)
        self.btn_decimal.setObjectName("btn_decimal")
        self.gridLayout_2.addWidget(self.btn_decimal, 5, 2, 1, 1)
        self.btn_number5 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number5.sizePolicy().hasHeightForWidth())
        self.btn_number5.setSizePolicy(sizePolicy)
        self.btn_number5.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number5.setMaximumSize(QtCore.QSize(90, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number5.setFont(font)
        self.btn_number5.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number5.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number5.setCheckable(True)
        self.btn_number5.setAutoDefault(False)
        self.btn_number5.setDefault(False)
        self.btn_number5.setFlat(False)
        self.btn_number5.setObjectName("btn_number5")
        self.gridLayout_2.addWidget(self.btn_number5, 3, 1, 1, 1)
        self.btn_number0 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number0.sizePolicy().hasHeightForWidth())
        self.btn_number0.setSizePolicy(sizePolicy)
        self.btn_number0.setMinimumSize(QtCore.QSize(193, 77))
        self.btn_number0.setMaximumSize(QtCore.QSize(193, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number0.setFont(font)
        self.btn_number0.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number0.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number0.setCheckable(True)
        self.btn_number0.setAutoDefault(False)
        self.btn_number0.setDefault(False)
        self.btn_number0.setFlat(False)
        self.btn_number0.setObjectName("btn_number0")
        self.gridLayout_2.addWidget(self.btn_number0, 5, 0, 1, 2)
        self.btn_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minus.sizePolicy().hasHeightForWidth())
        self.btn_minus.setSizePolicy(sizePolicy)
        self.btn_minus.setMinimumSize(QtCore.QSize(77, 70))
        self.btn_minus.setMaximumSize(QtCore.QSize(77, 80))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_minus.setFont(font)
        self.btn_minus.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_minus.setStyleSheet("background-color: rgb(254, 160, 10);\n"
"color: rgb(250, 250, 250);\n"
"border: none;")
        self.btn_minus.setCheckable(True)
        self.btn_minus.setAutoDefault(False)
        self.btn_minus.setDefault(False)
        self.btn_minus.setFlat(False)
        self.btn_minus.setObjectName("btn_minus")
        self.gridLayout_2.addWidget(self.btn_minus, 3, 3, 1, 1)
        self.btn_plus_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_plus_minus.sizePolicy().hasHeightForWidth())
        self.btn_plus_minus.setSizePolicy(sizePolicy)
        self.btn_plus_minus.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_plus_minus.setMaximumSize(QtCore.QSize(90, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_plus_minus.setFont(font)
        self.btn_plus_minus.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_plus_minus.setStyleSheet("QPushButton {\n"
"background-color: rgb(100, 100, 100);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(90, 90, 90);\n"
"}")
        self.btn_plus_minus.setCheckable(True)
        self.btn_plus_minus.setAutoDefault(False)
        self.btn_plus_minus.setDefault(False)
        self.btn_plus_minus.setFlat(False)
        self.btn_plus_minus.setObjectName("btn_plus_minus")
        self.gridLayout_2.addWidget(self.btn_plus_minus, 1, 1, 1, 1)
        self.btn_number1 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number1.sizePolicy().hasHeightForWidth())
        self.btn_number1.setSizePolicy(sizePolicy)
        self.btn_number1.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number1.setMaximumSize(QtCore.QSize(95, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number1.setFont(font)
        self.btn_number1.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number1.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}\n"
"")
        self.btn_number1.setCheckable(True)
        self.btn_number1.setAutoDefault(False)
        self.btn_number1.setDefault(False)
        self.btn_number1.setFlat(False)
        self.btn_number1.setObjectName("btn_number1")
        self.gridLayout_2.addWidget(self.btn_number1, 4, 0, 1, 1)
        self.btn_equals = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_equals.sizePolicy().hasHeightForWidth())
        self.btn_equals.setSizePolicy(sizePolicy)
        self.btn_equals.setMinimumSize(QtCore.QSize(77, 70))
        self.btn_equals.setMaximumSize(QtCore.QSize(77, 80))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_equals.setFont(font)
        self.btn_equals.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_equals.setStyleSheet("background-color: rgb(254, 160, 10);\n"
"color: rgb(250, 250, 250);\n"
"border: none;")
        self.btn_equals.setCheckable(True)
        self.btn_equals.setAutoDefault(False)
        self.btn_equals.setDefault(False)
        self.btn_equals.setFlat(False)
        self.btn_equals.setObjectName("btn_equals")
        self.gridLayout_2.addWidget(self.btn_equals, 5, 3, 1, 1)
        self.btn_number7 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number7.sizePolicy().hasHeightForWidth())
        self.btn_number7.setSizePolicy(sizePolicy)
        self.btn_number7.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number7.setMaximumSize(QtCore.QSize(95, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number7.setFont(font)
        self.btn_number7.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number7.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number7.setCheckable(True)
        self.btn_number7.setAutoDefault(False)
        self.btn_number7.setDefault(False)
        self.btn_number7.setFlat(False)
        self.btn_number7.setObjectName("btn_number7")
        self.gridLayout_2.addWidget(self.btn_number7, 2, 0, 1, 1)
        self.btn_number9 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number9.sizePolicy().hasHeightForWidth())
        self.btn_number9.setSizePolicy(sizePolicy)
        self.btn_number9.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number9.setMaximumSize(QtCore.QSize(85, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number9.setFont(font)
        self.btn_number9.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number9.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number9.setCheckable(True)
        self.btn_number9.setAutoDefault(False)
        self.btn_number9.setDefault(False)
        self.btn_number9.setFlat(False)
        self.btn_number9.setObjectName("btn_number9")
        self.gridLayout_2.addWidget(self.btn_number9, 2, 2, 1, 1)
        self.btn_perc = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_perc.sizePolicy().hasHeightForWidth())
        self.btn_perc.setSizePolicy(sizePolicy)
        self.btn_perc.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_perc.setMaximumSize(QtCore.QSize(90, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_perc.setFont(font)
        self.btn_perc.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_perc.setStyleSheet("QPushButton {\n"
"background-color: rgb(100, 100, 100);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(90, 90, 90);\n"
"}")
        self.btn_perc.setCheckable(True)
        self.btn_perc.setAutoDefault(False)
        self.btn_perc.setDefault(False)
        self.btn_perc.setFlat(False)
        self.btn_perc.setObjectName("btn_perc")
        self.gridLayout_2.addWidget(self.btn_perc, 1, 2, 1, 1)
        self.btn_number8 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number8.sizePolicy().hasHeightForWidth())
        self.btn_number8.setSizePolicy(sizePolicy)
        self.btn_number8.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number8.setMaximumSize(QtCore.QSize(90, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number8.setFont(font)
        self.btn_number8.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number8.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number8.setCheckable(False)
        self.btn_number8.setAutoDefault(False)
        self.btn_number8.setDefault(False)
        self.btn_number8.setFlat(False)
        self.btn_number8.setObjectName("btn_number8")
        self.gridLayout_2.addWidget(self.btn_number8, 2, 1, 1, 1)
        self.btn_number6 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_number6.sizePolicy().hasHeightForWidth())
        self.btn_number6.setSizePolicy(sizePolicy)
        self.btn_number6.setMinimumSize(QtCore.QSize(95, 77))
        self.btn_number6.setMaximumSize(QtCore.QSize(85, 77))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_number6.setFont(font)
        self.btn_number6.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_number6.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(250, 250, 250);\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(135, 135, 135);\n"
"}")
        self.btn_number6.setCheckable(True)
        self.btn_number6.setAutoDefault(False)
        self.btn_number6.setDefault(False)
        self.btn_number6.setFlat(False)
        self.btn_number6.setObjectName("btn_number6")
        self.gridLayout_2.addWidget(self.btn_number6, 3, 2, 1, 1)
        self.Display = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Display.setMinimumSize(QtCore.QSize(350, 120))
        self.Display.setMaximumSize(QtCore.QSize(350, 120))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.Display.setFont(font)
        self.Display.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.BlankCursor))
        self.Display.setMouseTracking(False)
        self.Display.setToolTipDuration(2)
        self.Display.setAutoFillBackground(False)
        self.Display.setStyleSheet("color: rgb(250, 250, 250);\n"
"border: none;")
        self.Display.setMaxLength(12)
        self.Display.setFrame(True)
        self.Display.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.Display.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.Display.setDragEnabled(True)
        self.Display.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
        self.Display.setObjectName("Display")
        self.gridLayout_2.addWidget(self.Display, 0, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.btn_mult.setText(_translate("MainWindow", "x"))
        self.btn_number2.setText(_translate("MainWindow", "2"))
        self.btn_number4.setText(_translate("MainWindow", "4"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_clear.setText(_translate("MainWindow", "AC"))
        self.btn_number3.setText(_translate("MainWindow", "3"))
        self.btn_division.setText(_translate("MainWindow", "÷"))
        self.btn_decimal.setText(_translate("MainWindow", ","))
        self.btn_number5.setText(_translate("MainWindow", "5"))
        self.btn_number0.setText(_translate("MainWindow", "0"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_plus_minus.setText(_translate("MainWindow", "+/-"))
        self.btn_number1.setText(_translate("MainWindow", "1"))
        self.btn_equals.setText(_translate("MainWindow", "="))
        self.btn_number7.setText(_translate("MainWindow", "7"))
        self.btn_number9.setText(_translate("MainWindow", "9"))
        self.btn_perc.setText(_translate("MainWindow", "%"))
        self.btn_number8.setText(_translate("MainWindow", "8"))
        self.btn_number6.setText(_translate("MainWindow", "6"))
